name: attempts

on: push

jobs:
  
  job-1:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: welcome message
        run: echo "You pushed some codes."
  
  job-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: job 2 step 1
        run: echo "This message is from Job 2 Step 1"

      - name: job 2 step 2
        run: | 
          echo "This message is from Job 2 step 2"
          echo "This message is also from Job 2 step 2"


