name: attempts

on: push

jobs:
  
  greeting_workflow:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: welcome message
        run: echo "You pushed some codes."